services:
  - type: static
    name: GTSA
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; font-src 'self' data: https:;"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /home
        destination: /index.html
      - type: rewrite
        source: /banking
        destination: /index.html
      - type: rewrite
        source: /investment
        destination: /index.html
      - type: rewrite
        source: /about
        destination: /index.html
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /insurance
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /verify-otp
        destination: /index.html
      - type: rewrite
        source: /transaction
        destination: /index.html
      - type: rewrite
        source: /investmentplans
        destination: /index.html
      - type: rewrite
        source: /signup
        destination: /index.html
      - type: rewrite
        source: /deposit
        destination: /index.html
      - type: rewrite
        source: /withdrawal
        destination: /index.html
      - type: rewrite
        source: /withdrawal-savings
        destination: /index.html
      - type: rewrite
        source: /contactform
        destination: /index.html
      - type: rewrite
        source: /invest-deposit
        destination: /index.html
      - type: rewrite
        source: /invaccform
        destination: /index.html
      - type: rewrite
        source: /edituser
        destination: /index.html
      - type: rewrite
        source: /receipt
        destination: /index.html
      - type: rewrite
        source: /user/*
        destination: /index.html
      - type: rewrite
        source: /internationalwire
        destination: /index.html
